dataset_yaml: datasets\rcp_bbox_v6_reshuffled\dataset_tiled1536.yaml
init_weights: runs/train/v6_yolov8l_1536_reshuffled_v3/weights/last.pt
classes: [0]
imgsz: 1536
batch: 4
epochs: 150
device: '0'
patience: 30
optimizer: AdamW
lr0: 0.0015
weight_decay: 0.0005
project: runs/train
name: v6_yolov8l_1536_reshuffled_v3
retina_masks: false
mask_ratio: 4
overlap_mask: true
cos_lr: true
mosaic: 0.0
auto_augment: null
erasing: 0.0
hsv_h: 0.015
hsv_s: 0.0
hsv_v: 0.3
translate: 0.05
scale: 0.2
degrees: 0.0
flipud: 0.5
fliplr: 0.5
mixup: 0.0
copy_paste: 0.0
workers: 8
cache: disk
resume: true